# Generated by Django 5.2.5 on 2025-09-09 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Login_info_new_p",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(default="Mr.", max_length=100)),
                ("lname", models.CharField(default="Unknown", max_length=100)),
                ("email", models.EmailField(max_length=50)),
                ("password", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="User_posts",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("post", models.CharField(max_length=100)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                (
                    "u_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.login_info_new_p",
                    ),
                ),
            ],
        ),
    ]
